Resources:
  cAdvisorTask:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: "cadvisor"
      ContainerDefinitions:
        - Name: "cadvisor"
          Image: "google/cadvisor:latest"
          Essential: "true"
          Memory: "300"
          MountPoints:
            - SourceVolume: "root"
              ContainerPath: "/rootfs"
              ReadOnly: "true"
            - SourceVolume: "var_run"
              ContainerPath: "/var/run"
              ReadOnly: "false"
            - SourceVolume: "sys"
              ContainerPath: "/sys"
              ReadOnly: "true"
            - SourceVolume: "var_lib_docker"
              ContainerPath: "/var/lib/docker"
              ReadOnly: "true"
            - SourceVolume: "dev_disk"
              ContainerPath: "/dev/disk"
              ReadOnly: "true"
            - SourceVolume: "cgroup"
              ContainerPath: "/sys/fs/cgroup"
              ReadOnly: "true"
          PortMappings:
            - ContainerPort: "8080"
              HostPort: "8080"
      Volumes:
        - Name: "root"
          Host:
            SourcePath: "/"
        - Name: "var_run"
          Host:
            SourcePath: "/var/run"
        - Name: "sys"
          Host:
            SourcePath: "/sys"
        - Name: "var_lib_docker"
          Host:
            SourcePath: "/var/lib/docker"
        - Name: "dev_disk"
          Host:
            SourcePath: "/dev/disk"
        - Name: "cgroup"
          Host:
            SourcePath: "/cgroup"
