---
Description: "s3 bucket stack"

Resources:
  LoadbalancerAccessLogBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "loadbalancer-accesslogs"

  LoadbalancerAccessLogBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: "LoadbalancerAccessLogBucket"
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              # http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-access-logs.html
              AWS: "582318560864"
            Action:
              - "s3:PutObject"
            Resource: "arn:aws:s3:::loadbalancer-accesslogs/*/AWSLogs/*"

